/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AppshellRouteImport } from './routes/_appshell'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppshellWorkspaceRouteImport } from './routes/_appshell.workspace'
import { Route as AppshellSummarizeRouteImport } from './routes/_appshell.summarize'
import { Route as AppshellSourcesRouteImport } from './routes/_appshell.sources'
import { Route as AppshellSettingsRouteImport } from './routes/_appshell.settings'
import { Route as AppshellSearchRouteImport } from './routes/_appshell.search'
import { Route as AppshellMemoryRouteImport } from './routes/_appshell.memory'
import { Route as AppshellDashboardRouteImport } from './routes/_appshell.dashboard'
import { Route as AppshellCompareRouteImport } from './routes/_appshell.compare'
import { Route as AppshellChecklistRouteImport } from './routes/_appshell.checklist'
import { Route as AppshellAnalyzeRouteImport } from './routes/_appshell.analyze'
import { Route as AppshellAlertsRouteImport } from './routes/_appshell.alerts'
import { Route as AppshellSourceIdRouteImport } from './routes/_appshell.source.$id'
import { Route as ApiPublicHooksRunAlertsRouteImport } from './routes/api/public/hooks/run-alerts'
import { Route as ApiPublicHooksIngestInpsRouteImport } from './routes/api/public/hooks/ingest-inps'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AppshellRoute = AppshellRouteImport.update({
  id: '/_appshell',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppshellWorkspaceRoute = AppshellWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AppshellRoute,
} as any)
const AppshellSummarizeRoute = AppshellSummarizeRouteImport.update({
  id: '/summarize',
  path: '/summarize',
  getParentRoute: () => AppshellRoute,
} as any)
const AppshellSourcesRoute = AppshellSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AppshellRoute,
} as any)
const AppshellSettingsRoute = AppshellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppshellRoute,
} as any)
const AppshellSearchRoute = AppshellSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppshellRoute,
} as any)
const AppshellMemoryRoute = AppshellMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AppshellRoute,
} as any)
const AppshellDashboardRoute = AppshellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppshellRoute,
} as any)
const AppshellCompareRoute = AppshellCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AppshellRoute,
} as any)
const AppshellChecklistRoute = AppshellChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => AppshellRoute,
} as any)
const AppshellAnalyzeRoute = AppshellAnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => AppshellRoute,
} as any)
const AppshellAlertsRoute = AppshellAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppshellRoute,
} as any)
const AppshellSourceIdRoute = AppshellSourceIdRouteImport.update({
  id: '/source/$id',
  path: '/source/$id',
  getParentRoute: () => AppshellRoute,
} as any)
const ApiPublicHooksRunAlertsRoute = ApiPublicHooksRunAlertsRouteImport.update({
  id: '/api/public/hooks/run-alerts',
  path: '/api/public/hooks/run-alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksIngestInpsRoute =
  ApiPublicHooksIngestInpsRouteImport.update({
    id: '/api/public/hooks/ingest-inps',
    path: '/api/public/hooks/ingest-inps',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/alerts': typeof AppshellAlertsRoute
  '/analyze': typeof AppshellAnalyzeRoute
  '/checklist': typeof AppshellChecklistRoute
  '/compare': typeof AppshellCompareRoute
  '/dashboard': typeof AppshellDashboardRoute
  '/memory': typeof AppshellMemoryRoute
  '/search': typeof AppshellSearchRoute
  '/settings': typeof AppshellSettingsRoute
  '/sources': typeof AppshellSourcesRoute
  '/summarize': typeof AppshellSummarizeRoute
  '/workspace': typeof AppshellWorkspaceRoute
  '/source/$id': typeof AppshellSourceIdRoute
  '/api/public/hooks/ingest-inps': typeof ApiPublicHooksIngestInpsRoute
  '/api/public/hooks/run-alerts': typeof ApiPublicHooksRunAlertsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/alerts': typeof AppshellAlertsRoute
  '/analyze': typeof AppshellAnalyzeRoute
  '/checklist': typeof AppshellChecklistRoute
  '/compare': typeof AppshellCompareRoute
  '/dashboard': typeof AppshellDashboardRoute
  '/memory': typeof AppshellMemoryRoute
  '/search': typeof AppshellSearchRoute
  '/settings': typeof AppshellSettingsRoute
  '/sources': typeof AppshellSourcesRoute
  '/summarize': typeof AppshellSummarizeRoute
  '/workspace': typeof AppshellWorkspaceRoute
  '/source/$id': typeof AppshellSourceIdRoute
  '/api/public/hooks/ingest-inps': typeof ApiPublicHooksIngestInpsRoute
  '/api/public/hooks/run-alerts': typeof ApiPublicHooksRunAlertsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_appshell': typeof AppshellRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_appshell/alerts': typeof AppshellAlertsRoute
  '/_appshell/analyze': typeof AppshellAnalyzeRoute
  '/_appshell/checklist': typeof AppshellChecklistRoute
  '/_appshell/compare': typeof AppshellCompareRoute
  '/_appshell/dashboard': typeof AppshellDashboardRoute
  '/_appshell/memory': typeof AppshellMemoryRoute
  '/_appshell/search': typeof AppshellSearchRoute
  '/_appshell/settings': typeof AppshellSettingsRoute
  '/_appshell/sources': typeof AppshellSourcesRoute
  '/_appshell/summarize': typeof AppshellSummarizeRoute
  '/_appshell/workspace': typeof AppshellWorkspaceRoute
  '/_appshell/source/$id': typeof AppshellSourceIdRoute
  '/api/public/hooks/ingest-inps': typeof ApiPublicHooksIngestInpsRoute
  '/api/public/hooks/run-alerts': typeof ApiPublicHooksRunAlertsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/login'
    | '/onboarding'
    | '/alerts'
    | '/analyze'
    | '/checklist'
    | '/compare'
    | '/dashboard'
    | '/memory'
    | '/search'
    | '/settings'
    | '/sources'
    | '/summarize'
    | '/workspace'
    | '/source/$id'
    | '/api/public/hooks/ingest-inps'
    | '/api/public/hooks/run-alerts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/login'
    | '/onboarding'
    | '/alerts'
    | '/analyze'
    | '/checklist'
    | '/compare'
    | '/dashboard'
    | '/memory'
    | '/search'
    | '/settings'
    | '/sources'
    | '/summarize'
    | '/workspace'
    | '/source/$id'
    | '/api/public/hooks/ingest-inps'
    | '/api/public/hooks/run-alerts'
  id:
    | '__root__'
    | '/'
    | '/_appshell'
    | '/accept-invite'
    | '/login'
    | '/onboarding'
    | '/_appshell/alerts'
    | '/_appshell/analyze'
    | '/_appshell/checklist'
    | '/_appshell/compare'
    | '/_appshell/dashboard'
    | '/_appshell/memory'
    | '/_appshell/search'
    | '/_appshell/settings'
    | '/_appshell/sources'
    | '/_appshell/summarize'
    | '/_appshell/workspace'
    | '/_appshell/source/$id'
    | '/api/public/hooks/ingest-inps'
    | '/api/public/hooks/run-alerts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppshellRoute: typeof AppshellRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ApiPublicHooksIngestInpsRoute: typeof ApiPublicHooksIngestInpsRoute
  ApiPublicHooksRunAlertsRoute: typeof ApiPublicHooksRunAlertsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_appshell': {
      id: '/_appshell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppshellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_appshell/workspace': {
      id: '/_appshell/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AppshellWorkspaceRouteImport
      parentRoute: typeof AppshellRoute
    }
    '/_appshell/summarize': {
      id: '/_appshell/summarize'
      path: '/summarize'
      fullPath: '/summarize'
      preLoaderRoute: typeof AppshellSummarizeRouteImport
      parentRoute: typeof AppshellRoute
    }
    '/_appshell/sources': {
      id: '/_appshell/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof AppshellSourcesRouteImport
      parentRoute: typeof AppshellRoute
    }
    '/_appshell/settings': {
      id: '/_appshell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppshellSettingsRouteImport
      parentRoute: typeof AppshellRoute
    }
    '/_appshell/search': {
      id: '/_appshell/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppshellSearchRouteImport
      parentRoute: typeof AppshellRoute
    }
    '/_appshell/memory': {
      id: '/_appshell/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof AppshellMemoryRouteImport
      parentRoute: typeof AppshellRoute
    }
    '/_appshell/dashboard': {
      id: '/_appshell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppshellDashboardRouteImport
      parentRoute: typeof AppshellRoute
    }
    '/_appshell/compare': {
      id: '/_appshell/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof AppshellCompareRouteImport
      parentRoute: typeof AppshellRoute
    }
    '/_appshell/checklist': {
      id: '/_appshell/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof AppshellChecklistRouteImport
      parentRoute: typeof AppshellRoute
    }
    '/_appshell/analyze': {
      id: '/_appshell/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AppshellAnalyzeRouteImport
      parentRoute: typeof AppshellRoute
    }
    '/_appshell/alerts': {
      id: '/_appshell/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppshellAlertsRouteImport
      parentRoute: typeof AppshellRoute
    }
    '/_appshell/source/$id': {
      id: '/_appshell/source/$id'
      path: '/source/$id'
      fullPath: '/source/$id'
      preLoaderRoute: typeof AppshellSourceIdRouteImport
      parentRoute: typeof AppshellRoute
    }
    '/api/public/hooks/run-alerts': {
      id: '/api/public/hooks/run-alerts'
      path: '/api/public/hooks/run-alerts'
      fullPath: '/api/public/hooks/run-alerts'
      preLoaderRoute: typeof ApiPublicHooksRunAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ingest-inps': {
      id: '/api/public/hooks/ingest-inps'
      path: '/api/public/hooks/ingest-inps'
      fullPath: '/api/public/hooks/ingest-inps'
      preLoaderRoute: typeof ApiPublicHooksIngestInpsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppshellRouteChildren {
  AppshellAlertsRoute: typeof AppshellAlertsRoute
  AppshellAnalyzeRoute: typeof AppshellAnalyzeRoute
  AppshellChecklistRoute: typeof AppshellChecklistRoute
  AppshellCompareRoute: typeof AppshellCompareRoute
  AppshellDashboardRoute: typeof AppshellDashboardRoute
  AppshellMemoryRoute: typeof AppshellMemoryRoute
  AppshellSearchRoute: typeof AppshellSearchRoute
  AppshellSettingsRoute: typeof AppshellSettingsRoute
  AppshellSourcesRoute: typeof AppshellSourcesRoute
  AppshellSummarizeRoute: typeof AppshellSummarizeRoute
  AppshellWorkspaceRoute: typeof AppshellWorkspaceRoute
  AppshellSourceIdRoute: typeof AppshellSourceIdRoute
}

const AppshellRouteChildren: AppshellRouteChildren = {
  AppshellAlertsRoute: AppshellAlertsRoute,
  AppshellAnalyzeRoute: AppshellAnalyzeRoute,
  AppshellChecklistRoute: AppshellChecklistRoute,
  AppshellCompareRoute: AppshellCompareRoute,
  AppshellDashboardRoute: AppshellDashboardRoute,
  AppshellMemoryRoute: AppshellMemoryRoute,
  AppshellSearchRoute: AppshellSearchRoute,
  AppshellSettingsRoute: AppshellSettingsRoute,
  AppshellSourcesRoute: AppshellSourcesRoute,
  AppshellSummarizeRoute: AppshellSummarizeRoute,
  AppshellWorkspaceRoute: AppshellWorkspaceRoute,
  AppshellSourceIdRoute: AppshellSourceIdRoute,
}

const AppshellRouteWithChildren = AppshellRoute._addFileChildren(
  AppshellRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppshellRoute: AppshellRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ApiPublicHooksIngestInpsRoute: ApiPublicHooksIngestInpsRoute,
  ApiPublicHooksRunAlertsRoute: ApiPublicHooksRunAlertsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
